name: KSharp Actions
on: [ push ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: 17

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3

      - name: Execute Tests
        run: ./gradlew build test
