name: KSharp Actions
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3

      - name: Execute Tests
        run: ./gradlew build test