name: KSharp Actions
on: [ push ]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.3

      - name: Execute Tests
        run: ./gradlew build test